(use-modules (guest test)
             (schingle query)
             (web uri)
             (web request))

(define-test (schingle query query->alist)
  (equal? (query->alist "") '())
  (equal? (query->alist "a=b&c=d") '(("a" . "b") ("c" . "d")))
  (equal? (query->alist "a=b&c=d&e=f") '(("a" . "b") ("c" . "d") ("e" . "f")))
  (equal? (query->alist "%2B%20%5C%26%25%3D=%2B%20%5C%26%25%3D") '(("+ \\&%=" . "+ \\&%="))))

(define-test (schingle query alist->query)
  (equal? (alist->query '()) "")
  (equal? (alist->query '(("a" . "b") ("c" . "d"))) "a=b&c=d")
  (equal? (alist->query '(("a" . "b") ("c" . "d") ("e" . "f"))) "a=b&c=d&e=f")
  (equal? (alist->query '(("+ \\&%=" . "+ \\&%="))) "%2B%20%5C%26%25%3D=%2B%20%5C%26%25%3D"))

(define-test (schingle query req-query)
  (equal? (req-query (build-request (string->uri "http://localhost"))) '())
  (equal? (req-query (build-request (string->uri "http://localhost?a=b&c=d")))
          '(("a" . "b") ("c" . "d"))))
