dist: bionic
language: generic

install:
  - curl https://raw.githubusercontent.com/Petelliott/guest/master/install.sh | bash
  - export GUILE_LOAD_PATH=$(realpath ..)

script:
  - guest test/ --cover "$(printf "schingle/%s " *.scm)" --cover-out coverage.info


after_success:
  - coveralls.sh coverage.info
