dist: bionic
language: generic

install:
  - curl https://raw.githubusercontent.com/Petelliott/guest/master/install.sh | bash
  - apt install autoconf
  - curl -Lv https://github.com/aconchillo/guile-json/archive/3.1.0.tar.gz | tar xzv
  - (cd guile-json*; autoreconf -vif; ./configure --prefix=/usr; make; sudo make install)

script:
  - GUILE_LOAD_PATH=$(realpath ..) guest test/ --cover "$(printf "schingle/%s " *.scm)" --cover-out coverage.info


after_success:
  - coveralls.sh coverage.info
